// core/examples/applaunchpad-example-react/src/views/home.js
import React, { Component, useState, useEffect } from 'react';
import {
  addInitListener,
  addContextUpdateListener,
  removeContextUpdateListener,
  removeInitListener
} from '@applaunchpad-project/client';

const Home = () => {
  const [message, setMessage] = useState(
    ''
  );
  const [initListener, setInitListener] = useState(
    null
  );
  const [contextUpdateListener, setContextUpdateListener] = useState(
    null
  );

  useEffect(() => {
    setInitListener(addInitListener(initialContext => {
      setMessage('AppLaunchpad Client initialized.')
    }));

    setContextUpdateListener(addContextUpdateListener(updatedContext => {
      setMessage('AppLaunchpad Client updated.');
    }));

    return function cleanup() {
      removeContextUpdateListener(contextUpdateListener);
      removeInitListener(initListener);
    }
  }, []);

  return (
    <div>
      <h1>Home</h1>
      <div>{message}</div>
    </div>
  );
}

export default Home;

// core/examples/applaunchpad-example-angular/src/app/home/home.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { addInitListener, addContextUpdateListener } from '@applaunchpad-project/client';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})
export class HomeComponent implements OnInit {
  public message: string;

  constructor(private ref: ChangeDetectorRef) {}

  ngOnInit() {
    addInitListener(initialContext => {
      this.message = 'AppLaunchpad Client initialized.';
      if (!this.ref['destroyed']) {
        this.ref.detectChanges();
      }
    });
    addContextUpdateListener(updatedContext => {
      this.message = 'AppLaunchpad Client updated.';
      if (!this.ref['destroyed']) {
        this.ref.detectChanges();
      }
    });
  }
}
