// core/examples/applaunchpad-example-react/src/views/sample1.js
import React from 'react';

const Sample1 = () => {
  return (
    <div>
      <h1>Sample 1</h1>
      AppLaunchpad ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
      dolore magna aliquyam erat, sed diam voluptua.
    </div>
  );
}

export default Sample1;

// core/examples/applaunchpad-example-vue/src/views/sample1.vue
<template>
  <div>
    <section class="fd-section">
      <div class="fd-section__header">
        <h1 class="fd-section__title">Sample 1</h1>
      </div>
      <div class="fd-panel">
        AppLaunchpad ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
      </div>
    </section>
  </div>
</template>

<script>
  export default {
    name: "sample1"
  }
</script>

<style scoped>
</style>
